source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Mutiple View' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTLinkingIOS',
  ]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'SSZipArchive'
  pod 'HandyJSON'
  pod 'Alamofire', '~>4.5'
end
